# Generated by Django 4.1.7 on 2023-03-01 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0003_alter_assignment_file_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 12, 18, 23, 457470)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='grading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Assignment.grading'),
            preserve_default=False,
        ),
    ]
