# Generated by Django 4.1.7 on 2023-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0004_submission_date_submission_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='feedback',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
