# Generated by Django 4.1.7 on 2023-03-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0005_grading_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='Assignment.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.student')),
            ],
        ),
    ]
